### ISSUE TITLE
Keypress not working / only release

### ISSUE THREAD

**Issue by tybaulk** [kapresoft/wow-addon-actionbar-plus#26]
Just a bit of feedback but when using the new keybinds they only work on release rather than down.

**Comment by kapresoft** [comment]
Hi @tybaulk , 
The Bindings.xml seems to only support a "CLICK <secure-action-template>:LeftClick|RightClick" setting which is a mouse click (release) and that's the reason it only works on release.  I'm going to try to spend some time to see if there is a way around this.  I definitely see the advantage of having a keydown instead of a keypress.  If you have any pointers to how to implement this, I welcome it.   Thank you for the feedback.

**Comment by kapresoft** [comment]
I just made it work with "AnyDown" programmatically.  I need to adjust the drag-and-drop code so it doesn't click when moving around.  I hopefully should be able to release a fix today. Thanks again!

**Comment by kapresoft** [comment]
I took at the ELVUI code just to get an idea of how the addon is implementing the drag and drop code (without clicking): it looks like ELVUI is doing some attributes "gymnastics" to circumvent the action button being clicked while dragging and dropping. It make take me a little longer to implement the "on key down" fix; give or take a week or two.

**Comment by tybaulk** [comment]
Sounds good! Will let you know if I find anything else.

**Comment by kapresoft** [comment]
Fixed in PR #27 / ActionbarPlus v[1.0.0.25](https://www.curseforge.com/wow/addons/actionbarplus/files/3949255)
