### ISSUE TITLE
M6 again

### ISSUE THREAD

**Issue by tflo** [kapresoft/wow-addon-actionbar-plus#289]
Hi Tony,

Sorry to start a new thread, but it seems you have some wild running GH script in place that forks every other issue into some custom "tracking" issue, which now results in a mess of resolved and unresolved issues, obscuring the main issue.

So probably better to start off new.

The cosmetics are solved. Labels are there and they are great, typographically.

Still the big thing in the room:

How to"retain" buttons with M6 macros assigned to them across various chars? 

To recall: The main point of ABP is to have button bars across chars, i.e non-char/spec-specific bars. (For spec/char-specific bars we do not need any helper addon, as this is provided by Blizz’ standard interface.)

So, let's translate this to buttons with M6 macros on them:  

M6, at login, creates macros according to what it sees is needed., i.e.– roughly –  what is used on action bar buttons. It does not see macros attributed to MBP buttons. It does not know that ABP exists.

**So, how to solve this thing?**

You mentioned somewhere that it was temporarily necessary to reload any profile, but I never really got what you meant with that.

– Tom

**Comment by nfet** [comment]
>To recall: The main point of ABP is to have button bars across chars, i.e non-char/spec-specific bars. (For spec/char-specific bars we do not need any helper addon, as this is provided by Blizz’ standard interface.)

ABP just allows you to create additional and more mobile bars. Albeit, the new Edit layout feature in WoW Retail has improved a bit.  The player is still subjected to limited number of bars though.
ABP has always used character-specific profiles because each class typically have different spells, etc, with the exception of frame positions where there is a setting to use global or character-specific positions.

Currently, the player has the ability to copy profiles from any character so you have a three options using the AceConfig profile UI built-in to ABP.  

Option C below might work for you.  I have been using Option B myself and just create a Template file that I use for new characters, else I copy the profiles from existing characters (Option A).

## Here are the following options you can try.

### Option A.  Copy ABP profile from an existing character

1.  Open Config by `/abp config` and navigate to the _Profiles_ view

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/74c0f524-4fe6-4168-b8af-4f3694c16ee6)

2.  Select the "Copy From" drop down, then select the character you want to copy. This should prompt you to reload.

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/f8ba6f9e-a132-450e-9482-25b9ad258ca3)

### Option B.  Create a Template and use this profile as a manual template
I use this option for new characters because I typically have the same layout and use a couple of bars with macros across my characters.

1.  Open Config by `/abp config` and navigate to the _Profiles_ view
2. Create a new profile titled `@Template` or to the same effect. (Reload)
3. Layout the bars,  setup all the common macros across characters.

You can then use this profile to do a "Copy From" for other characters.

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/e1c55a00-54b1-42f2-afd6-d558663fcb59)

### Option C.  Use a common profile across characters

1.  Open Config by `/abp config` and navigate to the _Profiles_ view
2. Create a new profile titled `Common` or to the same effect. (Reload)

For every character you play, you would have to manually switch to this "Common" profile initially by selecting "Common" in the Existing Profiles dropdown.   Then any subsequent change you make in ABP, should reflect on other characters using this profile.

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/10c7e240-239c-4087-9ead-da59efd6429e)

**Comment by tflo** [comment]
Hm. I guess we have some fundamental misunderstanding going on.

I am using the same profile on all chars. (Actually 2 profiles: 1 for the normal toons, one for the banker and Ah toons). But we'l leave out the AH toons here, so this translates to "1 profile ("Default") for all normal toons".

I tried your 1st suggestion ("Option A"):

1. I set up some M6 buttons on a ABP bar of the profile "Default" on toon A. 
2. I copied the "Default" profile to new one named "test_new".
3. I logged in on another char and loaded the "test_new".

Well, the result was as expected, i.e. as if I would just have loaded profile "Default" (the usual shared profile): The M6 buttons are there, but the mappings are wrong: One button had the macro as expected (coincidence, i suppose), the other two had a question mark and no associated M6 macro.

The misunderstanding probably is this:

With ABP, I do **not** use different profiles on my 20+ toons (except the AH and bankers, but let's forget those for the moment). All chars share a common profile named "Default". And for me, this is the point of using ABP in addition to Blizz’s bars, because Blizz’s bars do not allow me to have shared bars across toons, not even across specs.

It is good to have char/class/spec-specific bars (the Blizz bars), no doubt, it is necessary for the usual combat spells and such. But I need also non-char/class/spec specific (aka generic) bars for my toons, and that’s where ABP comes into play. 

Actually I’m using ABP like OPie: for generic stuff like e.g. toys or quest items. And I know, I could use OPie for all that, but for certain things it’s more comfortable to have it directly on the button instead of on a pop-up ring, hence ABP.

So, I guess this problem is not solvable:

M6 detects the macro associations to the Blizz bar buttons, and creates the corresponding macros at login (or at zone change or whatever). 

What I expect is that M6 creates also the macros for the actual ABP bars (where the buttons are always the same, since shared across chars). I guess the only way to solve this would be to find a way to make M6 think that an ABP bar is a Blizz bar at  login.

**Comment by tflo** [comment]
A little follow-up :)

When I opened this whole thing, I was really not aware of the complications, and how difficult it will be , because of the way M6 works.

You have achieved big things towards M6 compatibility, and I guess this will be completely sufficient for folks that are using different ABP profiles, probably the majority.

And I can live without it. I can split back my macro system into M6 and Blizz, and use Blizz macros on ABP buttons, and where it doesn't work (e.g overlong scripts), there is still OPie or simply direct keybinds to M6 w/o buttons.

Many thanks for your efforts. I think you are really a good developer, in the sense that you are open to new (meaningful?) suggestions, and finding creative ways to realize stuff. Whether it fails[^1] at the end does not matter.

– Tom

[^1]: "Fail" also includes an unacceptable ratio of time spent to benefit.

**Comment by nfet** [comment]
Hi Tom,

>Well, the result was as expected, i.e. as if I would just have loaded profile "Default" (the usual shared profile): The M6 buttons are there, but the mappings are wrong: One button had the macro as expected (coincidence, i suppose), the other two had a question mark and no associated M6 macro.

I had forgotten about the behavior on how the M6 maps the wrapper macros (_M6+s0<N> per character and they may or may not be the same.   I think the suggestion of option A, B and C was a bad idea on my part. I apologize.  

But I think all the use case for your usage pattern "should" be resolved when the ABP profile per character spec is implemented.   Unique profile class talent should have been implemented in ABP because a spell in talent A may not be available in talent B, etc.   This is a bad user experience for players who use ABP.

>M6 detects the macro associations to the Blizz bar buttons, and creates the corresponding macros at login (or at zone change or whatever).

M6 also loads the macro mapping based on class/spec profile as I've shown you on the previous posts.  M6 is really not doing anything complicated, it just did the right thing of storing data per-char-per-talent which ABP should have done in the first place.

I'm not sure when I'll be able to provide this "profile per class and talent" feature but I'll try to start working towards that goal.

>Many thanks for your efforts. I think you are really a good developer, in the sense that you are open to new (meaningful?) suggestions, and finding creative ways to realize stuff. Whether it fails[1](https://github.com/kapresoft/wow-addon-actionbar-plus/issues/289#user-content-fn-1-9e63382f2e826b25769d534da37351a7) in the end does not matter.

I appreciate your gracious remarks.  Thanks again.

-- Tony

**Comment by tflo** [comment]
> But I think all the use case for your usage pattern "should" be resolved when the ABP profile per character spec is implemented.

Looking forward to this :)

Sorry for the delayed response.
