### ISSUE TITLE
Keydown not always working

### ISSUE THREAD

**Issue by tybaulk** [kapresoft/wow-addon-actionbar-plus#36]
Using modifier macros sometimes they keyDown reverts to keyRelease.

**Comment by nfet** [comment]
I'm not sure if this is related, but I followed the behavior of elvui where if you are pressing the move modifier key, I set the event to fire on release, the revert back to keyDown when the move is completed, otherwise the action is triggered.  I think as a side effect, this will change the behavior a little bit.

Behavior is:
hold modifier key (SHIFT, ALT, CTRL), whatever is configured in blizz settings, event will trigger on release; else trigger will be in keydown.

**Comment by tybaulk** [comment]
Strange. Upon logging in the macro will work on keydown. However, after the first use it reverts to a keyrelease.

**Comment by kapresoft** [comment]
Fixed in #344
