### ISSUE TITLE
ActionButtonUseKeyDown

### ISSUE THREAD

**Issue by fireymerlin** [kapresoft/wow-addon-actionbar-plus#386]
**Describe the bug**
The addon is changing cVAR "ActionButtonUseKeyDown" to be 0.
It does not always change it, but it does most of the time for my characters.
I don't see any option in the addon to control that setting.
I want that setting to be 1.
This started with one of the recent updates to the addon.

**To Reproduce**
1. Log into a character in the game.

**Expected behavior**
I would expect the addon to not modify the cVAR "ActionButtonUseKeyDown"

**Operating System**
- OS: Windows 11
- Classic hardcore

**Additional context**
I've tested with ActionBarPlus enabled and disabled.  The cVAR is only being set if it is enabled.  I have other addons that will let me change the setting, but those addons have an option in their config.

**Comment by nfet** [comment]
Update to 2024.3.9 when you can.  I just pushed a release and should be available in Curse Forge app shortly.  

https://legacy.curseforge.com/wow/addons/actionbarplus/files/5226276

## Just a small note though
In retail, I don't have a choice but to set `ActionButtonUseKeyDown` to 0 when the Modifier key is pressed,  otherwise the button won't work.  The `ActionButtonUseKeyDown` is restored to 1 afterwards.  This behavior is only true if a modifier key is assigned in the Action Bars options in blizzard under "Lock Action Bars" settings.  

If this is an issue for you in Retail, just don't use the addon.  Thank you for filing the bug.
Please let me know if 2024.3.9 fixed the issue so I can close this bug.

Cheers and thank you for using ActionbarPlus.

**Comment by fireymerlin** [comment]
Just tried the latest version.  I'm no longer having the issue.
