### ISSUE TITLE
Actionbar positions are lost after re-enabling addon

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-actionbar-plus#4]
## Repro Steps

1.  With ActionbarPlus addon enabled, disable the addon and reload UI
     >Addons can be disabled by pressing Esc for the menu and then click "Addon"

2. Re-enable the addon and Reload

    **Result:**  Addons are rendered at the top-left of the page (default location)

**Comment by nfet** [comment]
This might be a little more interesting to solve, since data is lost after an addon is disabled. We could potentially just have a solid initial layout instead of just stacking the default enabled bars in the same location.

**Comment by tflo** [comment]
> since data is lost after an addon is disabled

It seems your addon isn't saving the position _at all_, so it gets auto-saved to the layout-local.txt file ( `../World of Warcraft/_retail_/WTF/Account/<number>/<realm>/<char>/layout-local.txt` )

This isn't good for two reasons:

- This is a very volatile, non-persistent "save", the addon data gets wiped from that file after any session without the addon loaded.
  - It is OK to save only there if an addon doesn't have permanent frames on screen (eg a ColorPicker frame), but in the case of ActionBarPlus the position of the frames is the second most important property (after the actual button content), and having to reposition after every other login or so absolutely destroys the usability of the addon.
- Besides that, it saves the position per char. This is a second usability killer, because it means I would have to position the bars on each of my 18 toons separatly. 
  - You are already using profiles for the bar layout and contents; the position should be saved as a profile property, so, if anyone doesn't want to use a global position he can always opt out by creating a char-specific profile.

> This might be a little more interesting to solve

I'm pretty sure you have an addon loaded that saves frame positions properly to its SavedVariables file (90% of the addons do that ;) Just check out how the addon does it.

– Tom

**Comment by nfet** [comment]
Hi Tom,
Yes. The addon isn't saving position right now.  I just haven't gotten around to looking at this yet. After reading your suggestions above, this now seems very trivial to do.  I will put a high priority on this and get this implemented.

Thanks and your feedback is sincerely appreciated.
- Tony

**Comment by nfet** [comment]
In release 1.0.2
- https://www.curseforge.com/wow/addons/actionbarplus/files/4012066
- https://github.com/kapresoft/wow-addon-actionbar-plus/releases/tag/1.0.2
