### ISSUE TITLE
Spell on key down

### ISSUE THREAD

**Issue by Crazlol** [kapresoft/wow-addon-actionbar-plus#427]
Is it possible to launch spell on key down instead of key up ?

Thanks by advance / your work :)

**Comment by nfet** [comment]
Hi @Crazlol, 
The key press behavior on the action buttons (ActionbarPlus actions or the Blizz actions) is controlled through the drag-key settings.

If the **Lock Action Bars** checkbox is NOT CHECKED, then the action always fires on key-up.  I think this is due to the drag behavior, i.e., you have to press keydown to drag an action button to another spot if lock is not enabled.

## To enable the key-down action behavior
Make sure the **Lock Action Bars** is CHECKED see (1) on the image. This should trigger key-down on the action buttons. If it doesn't try and toggle the value from CHECKED to UNCHECKED, then back to CHECKED.

I hope this helps. Otherwise, you will have to file a bug and document the behavior so I can fix.  Right now, I don't know of any outstanding bug regarding this behavior.

And THANK YOU for using the add-on! ❤️

![image](https://github.com/user-attachments/assets/9c6526d0-0291-47b3-9d22-b4fc474731b2)
